package views;

import controllers.GestionCitas;
import models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;


public class AdmisionPanel extends javax.swing.JPanel {
    
    private GestionCitas gestionCitas;
    private DefaultTableModel tableModel;

    public AdmisionPanel() {
        gestionCitas = new GestionCitas();
        initComponents();
        
        tableModel = (DefaultTableModel) table.getModel();
        cargarCitasConfirmadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnCheckin = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Admisión (Check-in / Check-out)");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hora", "Paciente", "DNI", "Médico", "Consultorio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnCheckin.setText("Check-in (Iniciar Atención)");
        btnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCheckin);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinActionPerformed
        realizarCheckin();
    }//GEN-LAST:event_btnCheckinActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarCitasConfirmadas();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void cargarCitasConfirmadas() {
        tableModel.setRowCount(0);
        for (Cita cita : gestionCitas.listarPorFecha(LocalDate.now())) {
            if (cita.getEstado() == EstadoCita.CONFIRMADA ||
                cita.getEstado() == EstadoCita.PROGRAMADA) {
                tableModel.addRow(new Object[]{
                    cita.getId(),
                    cita.getFechaHora().toLocalTime(),
                    cita.getPaciente().getNombreCompleto(),
                    cita.getPaciente().getDni(),
                    cita.getMedico().getNombreCompleto(),
                    cita.getConsultorio() != null ? cita.getConsultorio().getCodigo() : "Virtual",
                    cita.getEstado()
                });
            }
        }
    }

    private void realizarCheckin() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String idCita = (String) tableModel.getValueAt(selectedRow, 0);
        String paciente = (String) tableModel.getValueAt(selectedRow, 2);
        String dni = (String) tableModel.getValueAt(selectedRow, 3);

        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Confirmar check-in para " + paciente + " (DNI: " + dni + ")?",
            "Check-in", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (gestionCitas.iniciarAtencion(idCita)) {
                JOptionPane.showMessageDialog(this,
                    "Check-in realizado. El paciente está en sala de espera.");
                cargarCitasConfirmadas();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCheckin;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
