package views;

import controllers.*;
import models.*;
import models.Consultorio;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;


public class AgendaCitasPanel extends javax.swing.JPanel {
    
    private GestionCitas gestionCitas;
    private GestionPacientes gestionPacientes;
    private GestionEmpleados gestionEmpleados;
    private GestionConsultorios gestionConsultorios;
    private DefaultTableModel tableModel;

    public AgendaCitasPanel() {
        gestionCitas = new GestionCitas();
        gestionPacientes = new GestionPacientes();
        gestionEmpleados = new GestionEmpleados();
        gestionConsultorios = new GestionConsultorios();
        initComponents();
        
        tableModel = (DefaultTableModel) table.getModel();
        lblTitulo.setText("Agenda de Citas - " + LocalDate.now());
        cargarCitasDelDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnNuevaCita = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agenda de Citas");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hora", "Paciente", "Médico", "Consultorio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevaCita.setText("Nueva Cita");
        btnNuevaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCitaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnNuevaCita);

        btnConfirmar.setText("Confirmar Cita");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnConfirmar);

        btnCancelar.setText("Cancelar Cita");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCancelar);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCitaActionPerformed
        crearNuevaCita();
    }//GEN-LAST:event_btnNuevaCitaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        confirmarCita();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarCita();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarCitasDelDia();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void cargarCitasDelDia() {
        tableModel.setRowCount(0);
        for (Cita cita : gestionCitas.listarCitasDelDia()) {
            tableModel.addRow(new Object[]{
                cita.getId(),
                cita.getFechaHora().toLocalTime(),
                cita.getPaciente().getNombreCompleto(),
                cita.getMedico().getNombreCompleto(),
                cita.getConsultorio() != null ? cita.getConsultorio().getCodigo() : "Telemedicina",
                cita.getEstado()
            });
        }
    }

    private void crearNuevaCita() {
        JTextField txtDNIPaciente = new JTextField();
        JComboBox<Medico> cmbMedico = new JComboBox<>();
        for (Medico m : gestionEmpleados.listarMedicos()) {
            cmbMedico.addItem(m);
        }
        JComboBox<Consultorio> cmbConsultorio = new JComboBox<>();
        for (Consultorio c : gestionConsultorios.listarDisponibles()) {
            cmbConsultorio.addItem(c);
        }
        String[] horas = {"08:00", "09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00", "17:00"};
        JComboBox<String> cmbHora = new JComboBox<>(horas);
        String[] modalidades = {"PRESENCIAL", "TELEMEDICINA"};
        JComboBox<String> cmbModalidad = new JComboBox<>(modalidades);
        JTextArea txtMotivo = new JTextArea(3, 20);

        Object[] campos = {
            "DNI Paciente:", txtDNIPaciente,
            "Médico:", cmbMedico,
            "Hora:", cmbHora,
            "Consultorio:", cmbConsultorio,
            "Modalidad:", cmbModalidad,
            "Motivo:", new JScrollPane(txtMotivo)
        };

        int result = JOptionPane.showConfirmDialog(this, campos, "Nueva Cita",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                Paciente paciente = gestionPacientes.buscarPorDNI(txtDNIPaciente.getText());
                if (paciente == null) {
                    JOptionPane.showMessageDialog(this, "Paciente no encontrado");
                    return;
                }

                Medico medico = (Medico) cmbMedico.getSelectedItem();
                Consultorio consultorio = (Consultorio) cmbConsultorio.getSelectedItem();
                String[] horaPartes = ((String) cmbHora.getSelectedItem()).split(":");
                LocalDateTime fechaHora = LocalDateTime.of(LocalDate.now(),
                    LocalTime.of(Integer.parseInt(horaPartes[0]), Integer.parseInt(horaPartes[1])));
                Modalidad modalidad = Modalidad.valueOf((String) cmbModalidad.getSelectedItem());

                Cita cita = gestionCitas.crearCita(paciente, medico, consultorio,
                    fechaHora, modalidad, txtMotivo.getText());

                if (cita != null) {
                    JOptionPane.showMessageDialog(this, "Cita creada: " + cita.getId());
                    cargarCitasDelDia();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "No se pudo crear la cita. Verifique disponibilidad.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void confirmarCita() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String idCita = (String) tableModel.getValueAt(selectedRow, 0);
        if (gestionCitas.confirmarCita(idCita)) {
            JOptionPane.showMessageDialog(this, "Cita confirmada");
            cargarCitasDelDia();
        }
    }

    private void cancelarCita() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String motivo = JOptionPane.showInputDialog(this, "Motivo de cancelación:");
        if (motivo != null && !motivo.trim().isEmpty()) {
            String idCita = (String) tableModel.getValueAt(selectedRow, 0);
            if (gestionCitas.cancelarCita(idCita, motivo)) {
                JOptionPane.showMessageDialog(this, "Cita cancelada");
                cargarCitasDelDia();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnNuevaCita;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
