package views;

import controllers.*;
import models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 * Atención Médica Panel
 * Compatible con NetBeans GUI Builder
 */
public class AtencionMedicaPanel extends javax.swing.JPanel {
    
    private GestionCitas gestionCitas;
    private GestionConsultas gestionConsultas;
    private GestionAutenticacion gestionAuth;
    private DefaultTableModel tableModel;
    private Medico medicoActual;

    public AtencionMedicaPanel() {
        gestionCitas = new GestionCitas();
        gestionConsultas = new GestionConsultas();
        gestionAuth = new GestionAutenticacion();
        medicoActual = (Medico) gestionAuth.getUsuarioActual();
        initComponents();
        
        tableModel = (DefaultTableModel) tableCitas.getModel();
        lblTitulo.setText("Mis Consultas - Dr(a). " + medicoActual.getNombreCompleto());
        cargarCitasDelDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCitas = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnIniciarConsulta = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Mis Consultas");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        tableCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hora", "Paciente", "Estado", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCitas);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnIniciarConsulta.setText("Iniciar Consulta");
        btnIniciarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarConsultaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnIniciarConsulta);

        btnAtender.setText("Atender Paciente");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAtender);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarConsultaActionPerformed
        iniciarConsulta();
    }//GEN-LAST:event_btnIniciarConsultaActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        atenderPaciente();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarCitasDelDia();
    }//GEN-LAST:event_btnActualizarActionPerformed

    // ==================== LÓGICA DE NEGOCIO ====================

    private void cargarCitasDelDia() {
        tableModel.setRowCount(0);
        for (Cita cita : gestionCitas.listarCitasDelDia()) {
            if (cita.getMedico().equals(medicoActual) &&
                cita.getEstado() != EstadoCita.CANCELADA) {
                tableModel.addRow(new Object[]{
                    cita.getId(),
                    cita.getFechaHora().toLocalTime(),
                    cita.getPaciente().getNombreCompleto(),
                    cita.getEstado(),
                    cita.getMotivoConsulta()
                });
            }
        }
    }

    private void iniciarConsulta() {
        int selectedRow = tableCitas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String idCita = (String) tableModel.getValueAt(selectedRow, 0);
        Cita cita = gestionCitas.buscarPorID(idCita);

        if (cita == null) return;

        if (cita.getEstado() != EstadoCita.EN_SALA) {
            JOptionPane.showMessageDialog(this,
                "El paciente debe estar en sala (Check-in realizado)");
            return;
        }

        Consulta consulta = gestionConsultas.iniciarConsulta(cita);
        if (consulta != null) {
            JOptionPane.showMessageDialog(this, "Consulta iniciada: " + consulta.getId());
            cargarCitasDelDia();
        }
    }

    private void atenderPaciente() {
        int selectedRow = tableCitas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String idCita = (String) tableModel.getValueAt(selectedRow, 0);
        Cita cita = gestionCitas.buscarPorID(idCita);
        if (cita == null) return;

        // Buscar consulta asociada
        Consulta consulta = null;
        for (Consulta c : gestionConsultas.listarAbiertas()) {
            if (c.getCita().getId().equals(idCita)) {
                consulta = c;
                break;
            }
        }

        if (consulta == null) {
            JOptionPane.showMessageDialog(this, "Primero debe iniciar la consulta");
            return;
        }

        mostrarFormularioConsulta(consulta);
    }

    private void mostrarFormularioConsulta(Consulta consulta) {
        JTextArea txtAnamnesis = new JTextArea(3, 30);
        JTextArea txtExamenFisico = new JTextArea(3, 30);
        JTextField txtDiagnostico = new JTextField(30);
        JTextArea txtPlan = new JTextArea(3, 30);

        Object[] campos = {
            "Anamnesis:", new JScrollPane(txtAnamnesis),
            "Examen Físico:", new JScrollPane(txtExamenFisico),
            "Diagnóstico:", txtDiagnostico,
            "Plan:", new JScrollPane(txtPlan)
        };

        int result = JOptionPane.showConfirmDialog(this, campos, "Atención Médica",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            consulta.setAnamnesis(txtAnamnesis.getText());
            consulta.setExamenFisico(txtExamenFisico.getText());
            consulta.setPlan(txtPlan.getText());

            // Agregar diagnóstico
            if (!txtDiagnostico.getText().trim().isEmpty()) {
                Diagnostico diag = new Diagnostico("A00", txtDiagnostico.getText(), "Principal");
                consulta.agregarDiagnostico(diag);
            }
            String resumen = "Diagnóstico: " + txtDiagnostico.getText() + "\nPlan: " + txtPlan.getText();
            gestionConsultas.cerrarConsulta(consulta.getId(), resumen);

            JOptionPane.showMessageDialog(this, "Consulta finalizada exitosamente");
            cargarCitasDelDia();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnIniciarConsulta;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableCitas;
    // End of variables declaration//GEN-END:variables
}
