package views;

import controllers.*;
import models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class AtencionMedicaPanel extends javax.swing.JPanel {
    
    private GestionCitas gestionCitas;
    private GestionConsultas gestionConsultas;
    private GestionAutenticacion gestionAuth;
    private DefaultTableModel tableModel;
    private Medico medicoActual;

    public AtencionMedicaPanel() {
        gestionCitas = new GestionCitas();
        gestionConsultas = new GestionConsultas();
        gestionAuth = new GestionAutenticacion();
        medicoActual = (Medico) gestionAuth.getUsuarioActual();
        initComponents();
        
        tableModel = (DefaultTableModel) tableCitas.getModel();
        lblTitulo.setText("Mis Consultas - Dr(a). " + medicoActual.getNombreCompleto());
        cargarCitasDelDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCitas = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnIniciarConsulta = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Mis Consultas");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        tableCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hora", "Paciente", "DNI", "Estado", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCitas);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnIniciarConsulta.setText("Iniciar Consulta");
        btnIniciarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarConsultaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnIniciarConsulta);

        btnAtender.setText("Atender Paciente");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAtender);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarConsultaActionPerformed
        iniciarConsulta();
    }//GEN-LAST:event_btnIniciarConsultaActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        atenderPaciente();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarCitasDelDia();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void cargarCitasDelDia() {
        tableModel.setRowCount(0);
        for (Cita cita : gestionCitas.listarCitasDelDia()) {
            if (cita.getMedico().equals(medicoActual) &&
                cita.getEstado() != EstadoCita.CANCELADA) {
                tableModel.addRow(new Object[]{
                    cita.getId(),
                    cita.getFechaHora().toLocalTime(),
                    cita.getPaciente().getNombreCompleto(),
                    cita.getPaciente().getDni(),
                    cita.getEstado(),
                    cita.getMotivoConsulta()
                });
            }
        }
    }

    private void iniciarConsulta() {
        int selectedRow = tableCitas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String idCita = (String) tableModel.getValueAt(selectedRow, 0);
        Cita cita = gestionCitas.buscarPorID(idCita);

        if (cita == null) return;

        if (cita.getEstado() != EstadoCita.EN_SALA) {
            JOptionPane.showMessageDialog(this,
                "El paciente debe estar en sala (Check-in realizado)");
            return;
        }

        Consulta consulta = gestionConsultas.iniciarConsulta(cita);
        if (consulta != null) {
            JOptionPane.showMessageDialog(this, "Consulta iniciada: " + consulta.getId());
            cargarCitasDelDia();
        }
    }

    private void atenderPaciente() {
        int selectedRow = tableCitas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita");
            return;
        }

        String idCita = (String) tableModel.getValueAt(selectedRow, 0);
        Cita cita = gestionCitas.buscarPorID(idCita);
        if (cita == null) return;

        // Buscar consulta asociada
        Consulta consulta = null;
        for (Consulta c : gestionConsultas.listarAbiertas()) {
            if (c.getCita().getId().equals(idCita)) {
                consulta = c;
                break;
            }
        }

        if (consulta == null) {
            JOptionPane.showMessageDialog(this, "Primero debe iniciar la consulta");
            return;
        }

        mostrarFormularioConsulta(consulta);
    }

    private void mostrarFormularioConsulta(Consulta consulta) {
        // Campos del formulario principal
        JTextArea txtAnamnesis = new JTextArea(3, 30);
        JTextArea txtExamenFisico = new JTextArea(3, 30);
        JTextField txtDiagnostico = new JTextField(30);
        JTextArea txtPlan = new JTextArea(3, 30);

        // Lista de órdenes agregadas
        DefaultListModel<String> modeloOrdenes = new DefaultListModel<>();
        JList<String> listaOrdenes = new JList<>(modeloOrdenes);
        listaOrdenes.setVisibleRowCount(4);
        JScrollPane scrollOrdenes = new JScrollPane(listaOrdenes);

        // Panel de botones para agregar órdenes
        JPanel panelBotonesOrdenes = new JPanel();
        JButton btnAgregarLab = new JButton("➕ Laboratorio");
        JButton btnAgregarImagen = new JButton("➕ Imagen");
        JButton btnAgregarProc = new JButton("➕ Procedimiento");

        panelBotonesOrdenes.add(btnAgregarLab);
        panelBotonesOrdenes.add(btnAgregarImagen);
        panelBotonesOrdenes.add(btnAgregarProc);

        // Panel que contiene lista y botones de órdenes
        JPanel panelOrdenes = new JPanel(new BorderLayout());
        panelOrdenes.add(panelBotonesOrdenes, BorderLayout.NORTH);
        panelOrdenes.add(scrollOrdenes, BorderLayout.CENTER);

        // Listeners de botones
        btnAgregarLab.addActionListener(e -> agregarOrdenLaboratorio(consulta, modeloOrdenes));
        btnAgregarImagen.addActionListener(e -> agregarOrdenImagen(consulta, modeloOrdenes));
        btnAgregarProc.addActionListener(e -> agregarOrdenProcedimiento(consulta, modeloOrdenes));

        // Armar campos completos
        Object[] campos = {
            "Anamnesis:", new JScrollPane(txtAnamnesis),
            "Examen Físico:", new JScrollPane(txtExamenFisico),
            "Diagnóstico:", txtDiagnostico,
            "Plan:", new JScrollPane(txtPlan),
            "─────── Órdenes Médicas ───────", panelOrdenes
        };

        int result = JOptionPane.showConfirmDialog(this, campos, "Atención Médica",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            consulta.setAnamnesis(txtAnamnesis.getText());
            consulta.setExamenFisico(txtExamenFisico.getText());
            consulta.setPlan(txtPlan.getText());

            // Agregar diagnóstico
            if (!txtDiagnostico.getText().trim().isEmpty()) {
                Diagnostico diag = new Diagnostico("A00", txtDiagnostico.getText(), "Principal");
                consulta.agregarDiagnostico(diag);
            }
            String resumen = "Diagnóstico: " + txtDiagnostico.getText() + "\nPlan: " + txtPlan.getText();
            gestionConsultas.cerrarConsulta(consulta.getId(), resumen);

            JOptionPane.showMessageDialog(this, 
                "Consulta finalizada exitosamente\n" + 
                "Órdenes agregadas: " + consulta.getOrdenes().size());
            cargarCitasDelDia();
        }
    }

    private void agregarOrdenLaboratorio(Consulta consulta, DefaultListModel<String> modelo) {
        JTextField txtDescripcion = new JTextField(30);
        String[] tipos = {"Hematología", "Bioquímica", "Microbiología", "Inmunología", "Otros"};
        JComboBox<String> cmbTipo = new JComboBox<>(tipos);
        JCheckBox chkAyuno = new JCheckBox("Requiere ayuno");
        JTextField txtCosto = new JTextField("50.00", 10);

        Object[] campos = {
            "Descripción:", txtDescripcion,
            "Tipo de Análisis:", cmbTipo,
            chkAyuno,
            "Costo (S/.):", txtCosto
        };

        int result = JOptionPane.showConfirmDialog(this, campos, 
            "Agregar Orden de Laboratorio", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            try {
                String desc = txtDescripcion.getText().trim();
                if (desc.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Ingrese descripción");
                    return;
                }
                double costo = Double.parseDouble(txtCosto.getText());

                String id = utils.GeneradorID.generarIDOrden("LAB");
                OrdenLaboratorio orden = new OrdenLaboratorio(
                    id,
                    consulta.getCita().getPaciente(),
                    medicoActual,
                    desc,
                    (String) cmbTipo.getSelectedItem(),
                    chkAyuno.isSelected(),
                    costo
                );

                consulta.agregarOrden(orden);
                modelo.addElement(String.format("🔬 LAB - %s - S/. %.2f", desc, costo));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Costo inválido");
            }
        }
    }

    private void agregarOrdenImagen(Consulta consulta, DefaultListModel<String> modelo) {
        JTextField txtDescripcion = new JTextField(30);
        String[] tipos = {"Radiografía", "Ecografía", "Tomografía", "Resonancia", "Mamografía"};
        JComboBox<String> cmbTipo = new JComboBox<>(tipos);
        JTextField txtArea = new JTextField(20);
        JCheckBox chkContraste = new JCheckBox("Requiere contraste");
        JTextField txtCosto = new JTextField("80.00", 10);

        // Actualizar costo sugerido según tipo
        cmbTipo.addActionListener(e -> {
            String tipo = (String) cmbTipo.getSelectedItem();
            if (tipo != null) {
                switch (tipo) {
                    case "Radiografía": txtCosto.setText("80.00"); break;
                    case "Ecografía": txtCosto.setText("120.00"); break;
                    case "Tomografía": txtCosto.setText("250.00"); break;
                    case "Resonancia": txtCosto.setText("350.00"); break;
                    case "Mamografía": txtCosto.setText("100.00"); break;
                }
            }
        });

        Object[] campos = {
            "Descripción:", txtDescripcion,
            "Tipo de Imagen:", cmbTipo,
            "Área Anatómica:", txtArea,
            chkContraste,
            "Costo (S/.):", txtCosto
        };

        int result = JOptionPane.showConfirmDialog(this, campos, 
            "Agregar Orden de Imagen", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            try {
                String desc = txtDescripcion.getText().trim();
                String area = txtArea.getText().trim();
                if (desc.isEmpty() || area.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Complete todos los campos");
                    return;
                }
                double costo = Double.parseDouble(txtCosto.getText());

                String id = utils.GeneradorID.generarIDOrden("IMG");
                OrdenImagen orden = new OrdenImagen(
                    id,
                    consulta.getCita().getPaciente(),
                    medicoActual,
                    desc,
                    (String) cmbTipo.getSelectedItem(),
                    area,
                    chkContraste.isSelected(),
                    costo
                );

                consulta.agregarOrden(orden);
                modelo.addElement(String.format("📷 IMG - %s de %s - S/. %.2f", 
                    cmbTipo.getSelectedItem(), area, costo));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Costo inválido");
            }
        }
    }

    private void agregarOrdenProcedimiento(Consulta consulta, DefaultListModel<String> modelo) {
        JTextField txtDescripcion = new JTextField(30);
        String[] tipos = {"Curación", "Inyectable", "Nebulización", "Sutura", "Otro"};
        JComboBox<String> cmbTipo = new JComboBox<>(tipos);
        String[] frecuencias = {"Única vez", "Diaria", "Interdiaria", "Semanal"};
        JComboBox<String> cmbFrecuencia = new JComboBox<>(frecuencias);
        JSpinner spnSesiones = new JSpinner(new SpinnerNumberModel(1, 1, 30, 1));
        JTextField txtCosto = new JTextField("30.00", 10);

        // Actualizar costo sugerido según tipo
        cmbTipo.addActionListener(e -> {
            String tipo = (String) cmbTipo.getSelectedItem();
            if (tipo != null) {
                switch (tipo) {
                    case "Curación": txtCosto.setText("30.00"); break;
                    case "Inyectable": txtCosto.setText("20.00"); break;
                    case "Nebulización": txtCosto.setText("25.00"); break;
                    case "Sutura": txtCosto.setText("50.00"); break;
                    default: txtCosto.setText("30.00");
                }
            }
        });

        Object[] campos = {
            "Descripción:", txtDescripcion,
            "Tipo de Procedimiento:", cmbTipo,
            "Frecuencia:", cmbFrecuencia,
            "Cantidad de Sesiones:", spnSesiones,
            "Costo por Sesión (S/.):", txtCosto
        };

        int result = JOptionPane.showConfirmDialog(this, campos, 
            "Agregar Orden de Procedimiento", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            try {
                String desc = txtDescripcion.getText().trim();
                if (desc.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Ingrese descripción");
                    return;
                }
                double costo = Double.parseDouble(txtCosto.getText());
                int sesiones = (int) spnSesiones.getValue();

                String id = utils.GeneradorID.generarIDOrden("PROC");
                OrdenProcedimiento orden = new OrdenProcedimiento(
                    id,
                    consulta.getCita().getPaciente(),
                    medicoActual,
                    desc,
                    (String) cmbTipo.getSelectedItem(),
                    (String) cmbFrecuencia.getSelectedItem(),
                    sesiones,
                    costo
                );

                consulta.agregarOrden(orden);
                modelo.addElement(String.format("💉 PROC - %s (%d sesiones) - S/. %.2f c/u", 
                    desc, sesiones, costo));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Costo inválido");
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnIniciarConsulta;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableCitas;
    // End of variables declaration//GEN-END:variables
}
