package views;

import controllers.*;
import models.Consulta;
import models.*;
import models.Orden;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class FacturacionPanel extends javax.swing.JPanel {
    
    private GestionFacturacion gestionFacturacion;
    private GestionConsultas gestionConsultas;
    private GestionAutenticacion gestionAuth;
    private Factura facturaActual;
    private DefaultTableModel tableModel;

    public FacturacionPanel() {
        gestionFacturacion = new GestionFacturacion();
        gestionConsultas = new GestionConsultas();
        gestionAuth = new GestionAutenticacion();
        initComponents();
        
        tableModel = (DefaultTableModel) tablaConsultas.getModel();
        cargarConsultasCerradas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        lblConsultaID = new javax.swing.JLabel();
        txtConsultaID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFactura = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        btnGenerarFactura = new javax.swing.JButton();
        btnProcesarPago = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Facturación y Cobro");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        mainPanel.setLayout(new java.awt.BorderLayout(5, 5));

        topPanel.setLayout(new java.awt.BorderLayout());
        topPanel.setPreferredSize(new java.awt.Dimension(800, 250));

        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblConsultaID.setText("ID Consulta:");
        searchPanel.add(lblConsultaID);

        txtConsultaID.setColumns(15);
        searchPanel.add(txtConsultaID);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        searchPanel.add(btnBuscar);

        btnActualizarLista.setText("Actualizar Lista");
        btnActualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarListaActionPerformed(evt);
            }
        });
        searchPanel.add(btnActualizarLista);

        topPanel.add(searchPanel, java.awt.BorderLayout.NORTH);

        tablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Consulta", "Nº Cita", "Paciente", "DNI", "Doctor", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaConsultas);

        topPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        txtFactura.setEditable(false);
        txtFactura.setColumns(20);
        txtFactura.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtFactura.setRows(5);
        jScrollPane2.setViewportView(txtFactura);

        mainPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);

        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnGenerarFactura);

        btnProcesarPago.setText("Procesar Pago");
        btnProcesarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarPagoActionPerformed(evt);
            }
        });
        buttonPanel.add(btnProcesarPago);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarConsulta();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        generarFactura();
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnProcesarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarPagoActionPerformed
        procesarPago();
    }//GEN-LAST:event_btnProcesarPagoActionPerformed

    private void btnActualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarListaActionPerformed
        cargarConsultasCerradas();
        txtFactura.setText("");
        facturaActual = null;
        txtConsultaID.setText("");
    }//GEN-LAST:event_btnActualizarListaActionPerformed

    private void tablaConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConsultasMouseClicked
        int selectedRow = tablaConsultas.getSelectedRow();
        if (selectedRow != -1) {
            String idConsulta = (String) tableModel.getValueAt(selectedRow, 0);
            txtConsultaID.setText(idConsulta);
            buscarConsulta();
        }
    }//GEN-LAST:event_tablaConsultasMouseClicked


    private void cargarConsultasCerradas() {
        tableModel.setRowCount(0);
        
        for (Consulta consulta : Sistema.consultas) {
            if (consulta.isCerrada()) {
                tableModel.addRow(new Object[]{
                    consulta.getId(),
                    consulta.getCita().getId(),
                    consulta.getCita().getPaciente().getNombreCompleto(),
                    consulta.getCita().getPaciente().getDni(),
                    consulta.getCita().getMedico().getNombreCompleto(),
                    consulta.getFechaHoraInicio().toLocalDate()
                });
            }
        }
    }

    private void buscarConsulta() {
        String idConsulta = txtConsultaID.getText().trim();
        if (idConsulta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese ID de consulta o seleccione de la tabla");
            return;
        }

        Consulta consulta = gestionConsultas.buscarPorID(idConsulta);
        if (consulta == null) {
            JOptionPane.showMessageDialog(this, "Consulta no encontrada");
            return;
        }

        if (!consulta.isCerrada()) {
            JOptionPane.showMessageDialog(this,
                "La consulta debe estar cerrada para facturar");
            return;
        }

        txtFactura.setText("Consulta encontrada:\n\n" +
            "ID: " + consulta.getId() + "\n" +
            "Paciente: " + consulta.getCita().getPaciente().getNombreCompleto() + "\n" +
            "DNI: " + consulta.getCita().getPaciente().getDni() + "\n" +
            "Médico: " + consulta.getCita().getMedico().getNombreCompleto() + "\n" +
            "Fecha: " + consulta.getFechaHoraInicio().toLocalDate() + "\n\n" +
            "Presione 'Generar Factura' para continuar");
    }

    private void generarFactura() {
        String idConsulta = txtConsultaID.getText().trim();
        Consulta consulta = gestionConsultas.buscarPorID(idConsulta);

        if (consulta == null) {
            JOptionPane.showMessageDialog(this, "Primero busque una consulta");
            return;
        }

        facturaActual = gestionFacturacion.crearFactura(
            consulta.getCita().getPaciente(),
            consulta
        );

        ServicioConsulta servicio = new ServicioConsulta(
            consulta.getCita().getMedico().getEspecialidad(),
            consulta.getCita().getMedico().getNombreCompleto(),
            100.0  // Tarifa base
        );
        facturaActual.agregarItem(servicio);

        if (consulta.getOrdenes() != null) {
            for (Orden orden : consulta.getOrdenes()) {
                facturaActual.agregarItem(orden);
            }
        }

        txtFactura.setText(facturaActual.generarComprobante());
    }

    private void procesarPago() {
        if (facturaActual == null) {
            JOptionPane.showMessageDialog(this, "Primero genere una factura");
            return;
        }

        if (facturaActual.isPagado()) {
            JOptionPane.showMessageDialog(this, "Esta factura ya fue pagada");
            return;
        }

        String[] metodos = {"EFECTIVO", "TARJETA"};
        String metodo = (String) JOptionPane.showInputDialog(this,
            "Seleccione método de pago:", "Pago",
            JOptionPane.QUESTION_MESSAGE, null, metodos, metodos[0]);

        if (metodo != null) {
            MetodoPago metodoPago = MetodoPago.valueOf(metodo);
            String cajero = gestionAuth.getUsuarioActual().getNombreCompleto();

            gestionFacturacion.procesarPago(facturaActual.getNumeroFactura(),
                metodoPago, cajero);

            txtFactura.setText(facturaActual.generarComprobante());
            JOptionPane.showMessageDialog(this,
                "Pago procesado exitosamente\nNúmero de factura: " +
                facturaActual.getNumeroFactura());

            facturaActual = null;
            txtConsultaID.setText("");
            cargarConsultasCerradas();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarLista;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnProcesarPago;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConsultaID;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tablaConsultas;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtConsultaID;
    private javax.swing.JTextArea txtFactura;
    // End of variables declaration//GEN-END:variables
}
