package views;

import controllers.*;
import models.Consulta;
import models.*;
import models.Orden;
import javax.swing.*;
import java.awt.*;

/**
 * Facturación Panel
 * Compatible con NetBeans GUI Builder
 */
public class FacturacionPanel extends javax.swing.JPanel {
    
    private GestionFacturacion gestionFacturacion;
    private GestionConsultas gestionConsultas;
    private GestionAutenticacion gestionAuth;
    private Factura facturaActual;

    public FacturacionPanel() {
        gestionFacturacion = new GestionFacturacion();
        gestionConsultas = new GestionConsultas();
        gestionAuth = new GestionAutenticacion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        lblConsultaID = new javax.swing.JLabel();
        txtConsultaID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFactura = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        btnGenerarFactura = new javax.swing.JButton();
        btnProcesarPago = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Facturación y Cobro");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblConsultaID.setText("ID Consulta:");
        searchPanel.add(lblConsultaID);

        txtConsultaID.setColumns(15);
        searchPanel.add(txtConsultaID);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        searchPanel.add(btnBuscar);

        centerPanel.add(searchPanel, java.awt.BorderLayout.NORTH);

        txtFactura.setEditable(false);
        txtFactura.setColumns(20);
        txtFactura.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtFactura.setRows(5);
        jScrollPane1.setViewportView(txtFactura);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnGenerarFactura);

        btnProcesarPago.setText("Procesar Pago");
        btnProcesarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarPagoActionPerformed(evt);
            }
        });
        buttonPanel.add(btnProcesarPago);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarConsulta();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        generarFactura();
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnProcesarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarPagoActionPerformed
        procesarPago();
    }//GEN-LAST:event_btnProcesarPagoActionPerformed

    // ==================== LÓGICA DE NEGOCIO ====================

    private void buscarConsulta() {
        String idConsulta = txtConsultaID.getText().trim();
        if (idConsulta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese ID de consulta");
            return;
        }

        Consulta consulta = gestionConsultas.buscarPorID(idConsulta);
        if (consulta == null) {
            JOptionPane.showMessageDialog(this, "Consulta no encontrada");
            return;
        }

        if (!consulta.isCerrada()) {
            JOptionPane.showMessageDialog(this,
                "La consulta debe estar cerrada para facturar");
            return;
        }

        txtFactura.setText("Consulta encontrada:\n\n" +
            "ID: " + consulta.getId() + "\n" +
            "Paciente: " + consulta.getCita().getPaciente().getNombreCompleto() + "\n" +
            "Médico: " + consulta.getCita().getMedico().getNombreCompleto() + "\n" +
            "Fecha: " + consulta.getFechaHoraInicio().toLocalDate() + "\n\n" +
            "Presione 'Generar Factura' para continuar");
    }

    private void generarFactura() {
        String idConsulta = txtConsultaID.getText().trim();
        Consulta consulta = gestionConsultas.buscarPorID(idConsulta);

        if (consulta == null) {
            JOptionPane.showMessageDialog(this, "Primero busque una consulta");
            return;
        }

        // Crear factura
        facturaActual = gestionFacturacion.crearFactura(
            consulta.getCita().getPaciente(),
            consulta
        );

        // Agregar consulta como servicio
        ServicioConsulta servicio = new ServicioConsulta(
            consulta.getCita().getMedico().getEspecialidad(),
            consulta.getCita().getMedico().getNombreCompleto(),
            100.0  // Tarifa base
        );
        facturaActual.agregarItem(servicio);

        // Agregar órdenes si existen
        if (consulta.getOrdenes() != null) {
            for (Orden orden : consulta.getOrdenes()) {
                facturaActual.agregarItem(orden);
            }
        }

        // Mostrar factura
        txtFactura.setText(facturaActual.generarComprobante());
    }

    private void procesarPago() {
        if (facturaActual == null) {
            JOptionPane.showMessageDialog(this, "Primero genere una factura");
            return;
        }

        if (facturaActual.isPagado()) {
            JOptionPane.showMessageDialog(this, "Esta factura ya fue pagada");
            return;
        }

        String[] metodos = {"EFECTIVO", "TARJETA"};
        String metodo = (String) JOptionPane.showInputDialog(this,
            "Seleccione método de pago:", "Pago",
            JOptionPane.QUESTION_MESSAGE, null, metodos, metodos[0]);

        if (metodo != null) {
            MetodoPago metodoPago = MetodoPago.valueOf(metodo);
            String cajero = gestionAuth.getUsuarioActual().getNombreCompleto();

            gestionFacturacion.procesarPago(facturaActual.getNumeroFactura(),
                metodoPago, cajero);

            txtFactura.setText(facturaActual.generarComprobante());
            JOptionPane.showMessageDialog(this,
                "Pago procesado exitosamente\nNúmero de factura: " +
                facturaActual.getNumeroFactura());

            facturaActual = null;
            txtConsultaID.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnProcesarPago;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultaID;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField txtConsultaID;
    private javax.swing.JTextArea txtFactura;
    // End of variables declaration//GEN-END:variables
}
