package views;

import controllers.GestionConsultorios;
import models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class GestionConsultoriosPanel extends javax.swing.JPanel {
    
    private GestionConsultorios gestionConsultorios;
    private DefaultTableModel tableModel;

    public GestionConsultoriosPanel() {
        gestionConsultorios = new GestionConsultorios();
        initComponents();
        
        tableModel = (DefaultTableModel) table.getModel();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión de Consultorios");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Especialidad", "Piso", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnAgregar.setText("Agregar Consultorio");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAgregar);

        btnCambiarEstado.setText("Cambiar Estado");
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCambiarEstado);

        btnActualizar.setText("Actualizar Lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarConsultorio();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        cambiarEstado();
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void cargarDatos() {
        tableModel.setRowCount(0);
        for (Consultorio cons : gestionConsultorios.listarTodos()) {
            tableModel.addRow(new Object[]{
                cons.getCodigo(),
                cons.getNombre(),
                cons.getEspecialidad(),
                cons.getPiso(),
                cons.getEstado()
            });
        }
    }

    private void agregarConsultorio() {
        JTextField txtCodigo = new JTextField();
        JTextField txtNombre = new JTextField();
        JTextField txtEspecialidad = new JTextField();
        JTextField txtPiso = new JTextField();
        JTextField txtUbicacion = new JTextField();

        Object[] campos = {
            "Código:", txtCodigo,
            "Nombre:", txtNombre,
            "Especialidad:", txtEspecialidad,
            "Piso:", txtPiso,
            "Ubicación:", txtUbicacion
        };

        int result = JOptionPane.showConfirmDialog(this, campos, "Agregar Consultorio",
            JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            Consultorio consultorio = new Consultorio(
                txtCodigo.getText(),
                txtNombre.getText(),
                txtEspecialidad.getText(),
                txtPiso.getText(),
                txtUbicacion.getText()
            );

            if (gestionConsultorios.agregarConsultorio(consultorio)) {
                JOptionPane.showMessageDialog(this, "Consultorio agregado exitosamente");
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Error: Código duplicado");
            }
        }
    }

    private void cambiarEstado() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un consultorio");
            return;
        }

        String codigo = (String) tableModel.getValueAt(selectedRow, 0);
        EstadoConsultorio[] estados = EstadoConsultorio.values();
        EstadoConsultorio nuevoEstado = (EstadoConsultorio) JOptionPane.showInputDialog(
            this, "Seleccione el nuevo estado:", "Cambiar Estado",
            JOptionPane.QUESTION_MESSAGE, null, estados, estados[0]);

        if (nuevoEstado != null) {
            gestionConsultorios.cambiarEstado(codigo, nuevoEstado);
            JOptionPane.showMessageDialog(this, "Estado actualizado");
            cargarDatos();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
