package views;

import controllers.GestionEmpleados;
import models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;

public class GestionEmpleadosPanel extends javax.swing.JPanel {
    
    private GestionEmpleados gestionEmpleados;
    private DefaultTableModel tableModel;

    public GestionEmpleadosPanel() {
        gestionEmpleados = new GestionEmpleados();
        initComponents();
        
        tableModel = (DefaultTableModel) table.getModel();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión de Empleados");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre Completo", "Rol", "Usuario", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnAgregar.setText("Agregar Empleado");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAgregar);

        btnEliminar.setText("Eliminar Empleado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEliminar);

        btnActualizar.setText("Actualizar Lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarEmpleado();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarEmpleado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void cargarDatos() {
        tableModel.setRowCount(0);
        for (Empleado emp : gestionEmpleados.listarActivos()) {
            String nombreUsuario = "-";
            for (models.Usuario u : models.Sistema.usuarios) {
                if (u.getEmpleado() != null && u.getEmpleado().equals(emp)) {
                    nombreUsuario = u.getUsername();
                    break;
                }
            }
            
            tableModel.addRow(new Object[]{
                emp.getDni(),
                emp.getNombreCompleto(),
                emp.getRol(),
                nombreUsuario,
                emp.isActivo() ? "Activo" : "Inactivo"
            });
        }
    }

    private void agregarEmpleado() {
        JTextField txtDNI = new JTextField();
        JTextField txtNombres = new JTextField();
        JTextField txtApellidos = new JTextField();
        JTextField txtTelefono = new JTextField();
        JTextField txtEmail = new JTextField();
        JTextField txtUsuario = new JTextField();
        JPasswordField txtPassword = new JPasswordField();
        String[] roles = {"ADMINISTRADOR", "RECEPCIONISTA", "MEDICO", "ENFERMERO", "CAJERO"};
        JComboBox<String> cmbRol = new JComboBox<>(roles);

        Object[] campos = {
            "DNI:", txtDNI,
            "Nombres:", txtNombres,
            "Apellidos:", txtApellidos,
            "Teléfono:", txtTelefono,
            "Email:", txtEmail,
            "Rol:", cmbRol,
            "Usuario:", txtUsuario,
            "Contraseña:", txtPassword
        };

        int result = JOptionPane.showConfirmDialog(this, campos, "Agregar Empleado",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                Rol rol = Rol.valueOf((String) cmbRol.getSelectedItem());
                Empleado empleado;
                LocalDate fechaNac = LocalDate.of(1990, 1, 1);

                switch (rol) {
                    case MEDICO:
                        empleado = new Medico(txtDNI.getText(), txtNombres.getText(),
                            txtApellidos.getText(), fechaNac, "M",
                            txtTelefono.getText(), txtEmail.getText(), "",
                            "Medicina General", "");
                        break;
                    case RECEPCIONISTA:
                        empleado = new Recepcionista(txtDNI.getText(), txtNombres.getText(),
                            txtApellidos.getText(), fechaNac, "F",
                            txtTelefono.getText(), txtEmail.getText(), "",
                            "Mañana");
                        break;
                    case ENFERMERO:
                        empleado = new Enfermero(txtDNI.getText(), txtNombres.getText(),
                            txtApellidos.getText(), fechaNac, "F", 
                            txtTelefono.getText(), txtEmail.getText(), "",
                            "Consulta Externa", "Mañana");
                        break;
                    case CAJERO:
                        empleado = new Cajero(txtDNI.getText(), txtNombres.getText(),
                            txtApellidos.getText(), fechaNac, "F",
                            txtTelefono.getText(), txtEmail.getText(), "",
                            "1", "Mañana");
                        break;
                    default:
                        empleado = new Administrador(txtDNI.getText(), txtNombres.getText(),
                            txtApellidos.getText(), fechaNac, "M",
                            txtTelefono.getText(), txtEmail.getText(), "",
                            "Administración", "Administrador General");
                        break;
                }

                if (gestionEmpleados.agregarEmpleado(empleado, txtUsuario.getText(), new String(txtPassword.getPassword()))) {
                    JOptionPane.showMessageDialog(this, "Empleado agregado exitosamente");
                    cargarDatos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error: DNI duplicado o datos inválidos",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar empleado: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void eliminarEmpleado() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un empleado");
            return;
        }

        String dni = (String) tableModel.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este empleado?", "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (gestionEmpleados.eliminarEmpleado(dni)) {
                JOptionPane.showMessageDialog(this, "Empleado eliminado exitosamente");
                cargarDatos();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
