package views;

import controllers.GestionPacientes;
import models.Paciente;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;

public class GestionPacientesPanel extends javax.swing.JPanel {
    
    private GestionPacientes gestionPacientes;
    private DefaultTableModel tableModel;

    public GestionPacientesPanel() {
        gestionPacientes = new GestionPacientes();
        initComponents();
        
        tableModel = (DefaultTableModel) table.getModel();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        topPanel.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión de Pacientes");
        topPanel.add(lblTitulo, java.awt.BorderLayout.NORTH);

        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblBuscar.setText("Buscar:");
        searchPanel.add(lblBuscar);

        txtBuscar.setColumns(20);
        searchPanel.add(txtBuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        searchPanel.add(btnBuscar);

        topPanel.add(searchPanel, java.awt.BorderLayout.SOUTH);

        add(topPanel, java.awt.BorderLayout.NORTH);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre Completo", "Fecha Nac.", "Teléfono", "Historia Clínica"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnAgregar.setText("Registrar Paciente");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAgregar);

        btnActualizar.setText("Actualizar Lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnActualizar);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarPaciente();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        registrarPaciente();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void cargarDatos() {
        tableModel.setRowCount(0);
        for (Paciente pac : gestionPacientes.listarActivos()) {
            tableModel.addRow(new Object[]{
                pac.getDni(),
                pac.getNombreCompleto(),
                pac.getFechaNacimiento(),
                pac.getTelefono(),
                pac.getNumeroHistoriaClinica() != null ? pac.getNumeroHistoriaClinica() : "Sin asignar"
            });
        }
    }

    private void buscarPaciente() {
        String termino = txtBuscar.getText().trim();
        if (termino.isEmpty()) {
            cargarDatos();
            return;
        }

        tableModel.setRowCount(0);
        Paciente paciente = gestionPacientes.buscarPorDNI(termino);
        if (paciente != null) {
            tableModel.addRow(new Object[]{
                paciente.getDni(),
                paciente.getNombreCompleto(),
                paciente.getFechaNacimiento(),
                paciente.getTelefono(),
                paciente.getNumeroHistoriaClinica()
            });
        } else {
            for (Paciente pac : gestionPacientes.buscarPorNombre(termino)) {
                tableModel.addRow(new Object[]{
                    pac.getDni(),
                    pac.getNombreCompleto(),
                    pac.getFechaNacimiento(),
                    pac.getTelefono(),
                    pac.getNumeroHistoriaClinica()
                });
            }
        }
    }

    private void registrarPaciente() {
        JTextField txtDNI = new JTextField();
        JTextField txtNombres = new JTextField();
        JTextField txtApellidos = new JTextField();
        JTextField txtTelefono = new JTextField();
        JTextField txtEmail = new JTextField();
        JTextField txtDireccion = new JTextField();
        String[] sexos = {"M", "F"};
        JComboBox<String> cmbSexo = new JComboBox<>(sexos);
        JTextField txtContactoEmergencia = new JTextField();
        JTextField txtTelefonoEmergencia = new JTextField();

        Object[] campos = {
            "DNI:", txtDNI,
            "Nombres:", txtNombres,
            "Apellidos:", txtApellidos,
            "Sexo:", cmbSexo,
            "Teléfono:", txtTelefono,
            "Email:", txtEmail,
            "Dirección:", txtDireccion,
            "Contacto Emergencia:", txtContactoEmergencia,
            "Teléfono Emergencia:", txtTelefonoEmergencia
        };

        int result = JOptionPane.showConfirmDialog(this, campos, "Registrar Paciente",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                Paciente paciente = new Paciente(
                    txtDNI.getText(),
                    txtNombres.getText(),
                    txtApellidos.getText(),
                    LocalDate.of(1990, 1, 1), // Fecha por defecto
                    (String) cmbSexo.getSelectedItem(),
                    txtTelefono.getText(),
                    txtEmail.getText(),
                    txtDireccion.getText(),
                    "DNI",
                    txtContactoEmergencia.getText(),
                    txtTelefonoEmergencia.getText(),
                    "Familiar"
                );

                if (gestionPacientes.registrarPaciente(paciente)) {
                    JOptionPane.showMessageDialog(this,
                        "Paciente registrado exitosamente\nHistoria Clínica: " +
                        paciente.getNumeroHistoriaClinica());
                    cargarDatos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error: DNI duplicado o datos inválidos",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al registrar paciente: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable table;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
