package views;

import controllers.*;
import models.*;
import models.Paciente;
import javax.swing.*;
import java.awt.*;

public class HistoriaClinicaPanel extends javax.swing.JPanel {
    
    private GestionPacientes gestionPacientes;

    public HistoriaClinicaPanel() {
        gestionPacientes = new GestionPacientes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistoria = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout(10, 10));

        topPanel.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Historia Clínica");
        topPanel.add(lblTitulo, java.awt.BorderLayout.NORTH);

        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblBuscar.setText("DNI o Historia Clínica:");
        searchPanel.add(lblBuscar);

        txtBuscar.setColumns(20);
        searchPanel.add(txtBuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        searchPanel.add(btnBuscar);

        topPanel.add(searchPanel, java.awt.BorderLayout.SOUTH);

        add(topPanel, java.awt.BorderLayout.NORTH);

        txtHistoria.setEditable(false);
        txtHistoria.setColumns(20);
        txtHistoria.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtHistoria.setRows(5);
        jScrollPane1.setViewportView(txtHistoria);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarHistoria();
    }//GEN-LAST:event_btnBuscarActionPerformed


    private void buscarHistoria() {
        String termino = txtBuscar.getText().trim();
        if (termino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese DNI o número de historia clínica");
            return;
        }

        Paciente paciente = gestionPacientes.buscarPorDNI(termino);
        if (paciente == null) {
            paciente = gestionPacientes.buscarPorHistoriaClinica(termino);
        }

        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Paciente no encontrado");
            txtHistoria.setText("");
            return;
        }

        HistoriaClinica historia = gestionPacientes.obtenerHistoriaClinica(paciente);
        if (historia == null) {
            JOptionPane.showMessageDialog(this, "No se encontró historia clínica");
            return;
        }

        mostrarHistoria(historia);
    }

    private void mostrarHistoria(HistoriaClinica historia) {
        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════════════════════\n");
        sb.append("                   HISTORIA CLÍNICA\n");
        sb.append("═══════════════════════════════════════════════════════\n");
        sb.append("HC: ").append(historia.getNumeroHistoriaClinica()).append("\n");
        sb.append("Paciente: ").append(historia.getPaciente().getNombreCompleto()).append("\n");
        sb.append("DNI: ").append(historia.getPaciente().getDni()).append("\n");
        sb.append("Fecha Apertura: ").append(historia.getFechaApertura()).append("\n");
        sb.append("───────────────────────────────────────────────────────\n");

        if (historia.getConsultas().isEmpty()) {
            sb.append("Sin consultas registradas\n");
        } else {
            sb.append("CONSULTAS:\n\n");
            for (Consulta consulta : historia.getConsultas()) {
                sb.append("Consulta: ").append(consulta.getId()).append("\n");
                sb.append("Fecha: ").append(consulta.getFechaHoraInicio()).append("\n");
                sb.append("Médico: ").append(consulta.getCita().getMedico().getNombreCompleto()).append("\n");
                sb.append("Motivo: ").append(consulta.getMotivoConsulta()).append("\n");

                if (consulta.getDiagnosticos() != null && !consulta.getDiagnosticos().isEmpty()) {
                    sb.append("Diagnósticos:\n");
                    for (Diagnostico diag : consulta.getDiagnosticos()) {
                        sb.append("  - ").append(diag).append("\n");
                    }
                }

                if (consulta.getResumenClinico() != null) {
                    sb.append("Resumen: ").append(consulta.getResumenClinico()).append("\n");
                }

                sb.append("\n");
            }
        }

        sb.append("═══════════════════════════════════════════════════════\n");
        txtHistoria.setText(sb.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtHistoria;
    // End of variables declaration//GEN-END:variables
}
