package views;

import javax.swing.*;
import java.awt.*;
import models.Usuario;

/**
 * Main Dashboard
 * Compatible con NetBeans GUI Builder
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private Usuario usuario;

    public MainDashboard(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        
        lblWelcome.setText("Bienvenido: " + usuario.getEmpleado().getNombreCompleto());
        setTitle("Sistema Médico - " + usuario.getRol());
        
        crearMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlMain = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Médico");

        pnlMain.setLayout(new java.awt.GridBagLayout());

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome.setText("Bienvenido: ");
        pnlMain.add(lblWelcome, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void crearMenu() {
        JMenuBar menuBar = new JMenuBar();
        
        JMenu menuArchivo = new JMenu("Archivo");
        JMenuItem itemSalir = new JMenuItem("Salir");
        itemSalir.addActionListener(e -> System.exit(0));
        menuArchivo.add(itemSalir);
        menuBar.add(menuArchivo);
        
        if (usuario.getRol().equals("Administrador")) {
            JMenu menuAdmin = new JMenu("Administración");
            JMenuItem itemEmp = new JMenuItem("Gestionar Empleados");
            itemEmp.addActionListener(e -> new GestionEmpleadosView().setVisible(true));
            menuAdmin.add(itemEmp);
            JMenuItem itemCons = new JMenuItem("Gestionar Consultorios");
            menuAdmin.add(itemCons);
            menuBar.add(menuAdmin);
        }
        
        if (usuario.getRol().equals("Recepcionista") || usuario.getRol().equals("Administrador")) {
            JMenu menuRecep = new JMenu("Recepción");
            JMenuItem itemPac = new JMenuItem("Gestionar Pacientes");
            menuRecep.add(itemPac);
            JMenuItem itemCitas = new JMenuItem("Agenda / Citas");
            menuRecep.add(itemCitas);
            menuBar.add(menuRecep);
        }
        
        if (usuario.getRol().equals("Medico")) {
            JMenu menuMed = new JMenu("Médico");
            JMenuItem itemAgenda = new JMenuItem("Mi Agenda");
            menuMed.add(itemAgenda);
            menuBar.add(menuMed);
        }
        
        setJMenuBar(menuBar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
