package views;

import controllers.*;
import models.*;
import views.*;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {
    
    private GestionAutenticacion gestionAuth;
    private Empleado usuarioActual;

    public MainFrame() {
        gestionAuth = new GestionAutenticacion();
        usuarioActual = gestionAuth.getUsuarioActual();
        initComponents();
        lblUsuario.setText("Usuario: " + usuarioActual.getNombreCompleto() +
                               " (" + usuarioActual.getRol() + ")");
        
        JMenuBar menuBar = new JMenuBar();
        crearMenuSegunRol(menuBar);
        setJMenuBar(menuBar);
        
        setSize(1200, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Clínica");

        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(41, 128, 185));
        topPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.setLayout(new java.awt.BorderLayout());

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario: ");
        topPanel.add(lblUsuario, java.awt.BorderLayout.WEST);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        topPanel.add(btnCerrarSesion, java.awt.BorderLayout.EAST);

        mainPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        contentPanel.setLayout(new java.awt.BorderLayout());

        lblBienvenida.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido al Sistema de Gestión Clínica");
        contentPanel.add(lblBienvenida, java.awt.BorderLayout.CENTER);

        mainPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    private void crearMenuSegunRol(JMenuBar menuBar) {
        Rol rol = usuarioActual.getRol();

        switch (rol) {
            case ADMINISTRADOR:
                crearMenuAdministrador(menuBar);
                break;
            case RECEPCIONISTA:
                crearMenuRecepcionista(menuBar);
                break;
            case MEDICO:
                crearMenuMedico(menuBar);
                break;
            case ENFERMERO:
                crearMenuEnfermero(menuBar);
                break;
            case CAJERO:
                crearMenuCajero(menuBar);
                break;
        }
    }

    private void crearMenuAdministrador(JMenuBar menuBar) {
        JMenu menuEmpleados = new JMenu("Empleados");
        JMenuItem itemGestionEmpleados = new JMenuItem("Gestionar Empleados");
        itemGestionEmpleados.addActionListener(e -> mostrarPanel(new GestionEmpleadosPanel()));
        menuEmpleados.add(itemGestionEmpleados);
        menuBar.add(menuEmpleados);

        JMenu menuConsultorios = new JMenu("Infraestructura");
        JMenuItem itemGestionConsultorios = new JMenuItem("Gestionar Consultorios");
        itemGestionConsultorios.addActionListener(e -> mostrarPanel(new GestionConsultoriosPanel()));
        menuConsultorios.add(itemGestionConsultorios);
        menuBar.add(menuConsultorios);

        JMenu menuReportes = new JMenu("Reportes");
        JMenuItem itemReportes = new JMenuItem("Ver Reportes");
        itemReportes.addActionListener(e -> mostrarPanel(new ReportesPanel()));
        menuReportes.add(itemReportes);
        menuBar.add(menuReportes);
    }

    private void crearMenuRecepcionista(JMenuBar menuBar) {
        JMenu menuPacientes = new JMenu("Pacientes");
        JMenuItem itemGestionPacientes = new JMenuItem("Gestionar Pacientes");
        itemGestionPacientes.addActionListener(e -> mostrarPanel(new GestionPacientesPanel()));
        menuPacientes.add(itemGestionPacientes);
        menuBar.add(menuPacientes);

        JMenu menuCitas = new JMenu("Citas");
        JMenuItem itemAgenda = new JMenuItem("Agenda de Citas");
        itemAgenda.addActionListener(e -> mostrarPanel(new AgendaCitasPanel()));
        menuCitas.add(itemAgenda);
        menuBar.add(menuCitas);

        JMenu menuAdmision = new JMenu("Admisión");
        JMenuItem itemAdmision = new JMenuItem("Check-in / Check-out");
        itemAdmision.addActionListener(e -> mostrarPanel(new AdmisionPanel()));
        menuAdmision.add(itemAdmision);
        menuBar.add(menuAdmision);
    }

    private void crearMenuMedico(JMenuBar menuBar) {
        JMenu menuAtencion = new JMenu("Atención Médica");
        JMenuItem itemAtencion = new JMenuItem("Mis Consultas");
        itemAtencion.addActionListener(e -> mostrarPanel(new AtencionMedicaPanel()));
        menuAtencion.add(itemAtencion);
        menuBar.add(menuAtencion);

        JMenu menuHistoria = new JMenu("Historia Clínica");
        JMenuItem itemHistoria = new JMenuItem("Ver Historias Clínicas");
        itemHistoria.addActionListener(e -> mostrarPanel(new HistoriaClinicaPanel()));
        menuHistoria.add(itemHistoria);
        menuBar.add(menuHistoria);
    }

    private void crearMenuEnfermero(JMenuBar menuBar) {
        JMenu menuEnfermeria = new JMenu("Enfermería");
        JMenuItem itemSignosVitales = new JMenuItem("Registrar Signos Vitales");
        itemSignosVitales.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Función disponible en el módulo de atención médica");
        });
        menuEnfermeria.add(itemSignosVitales);
        menuBar.add(menuEnfermeria);
    }

    private void crearMenuCajero(JMenuBar menuBar) {
        JMenu menuFacturacion = new JMenu("Facturación");
        JMenuItem itemFacturar = new JMenuItem("Facturar y Cobrar");
        itemFacturar.addActionListener(e -> mostrarPanel(new FacturacionPanel()));
        menuFacturacion.add(itemFacturar);
        menuBar.add(menuFacturacion);
    }

    private void mostrarPanel(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    private void cerrarSesion() {
        int opcion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de cerrar sesión?",
            "Confirmar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            gestionAuth.cerrarSesion();
            dispose();
            new LoginFrame().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
