package views;

import controllers.*;
import models.*;
import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.Map;

public class ReportesPanel extends javax.swing.JPanel {
    
    private GestionFacturacion gestionFacturacion;
    private GestionCitas gestionCitas;
    private GestionConsultorios gestionConsultorios;
    private GestionEmpleados gestionEmpleados;
    private GestionConsultas gestionConsultas;

    public ReportesPanel() {
        gestionFacturacion = new GestionFacturacion();
        gestionCitas = new GestionCitas();
        gestionConsultorios = new GestionConsultorios();
        gestionEmpleados = new GestionEmpleados();
        gestionConsultas = new GestionConsultas();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        btnIngresosDiarios = new javax.swing.JButton();
        btnIngresosMensuales = new javax.swing.JButton();
        btnOcupacionConsultorios = new javax.swing.JButton();
        btnProduccionMedicos = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Reportes y Estadísticas");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        txtReporte.setEditable(false);
        txtReporte.setColumns(20);
        txtReporte.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtReporte.setRows(5);
        jScrollPane1.setViewportView(txtReporte);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        buttonPanel.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        btnIngresosDiarios.setText("Ingresos del Día");
        btnIngresosDiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosDiariosActionPerformed(evt);
            }
        });
        buttonPanel.add(btnIngresosDiarios);

        btnIngresosMensuales.setText("Ingresos del Mes");
        btnIngresosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosMensualesActionPerformed(evt);
            }
        });
        buttonPanel.add(btnIngresosMensuales);

        btnOcupacionConsultorios.setText("Ocupación Consultorios");
        btnOcupacionConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupacionConsultoriosActionPerformed(evt);
            }
        });
        buttonPanel.add(btnOcupacionConsultorios);

        btnProduccionMedicos.setText("Producción por Médico");
        btnProduccionMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduccionMedicosActionPerformed(evt);
            }
        });
        buttonPanel.add(btnProduccionMedicos);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresosDiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosDiariosActionPerformed
        mostrarIngresosDiarios();
    }//GEN-LAST:event_btnIngresosDiariosActionPerformed

    private void btnIngresosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosMensualesActionPerformed
        mostrarIngresosMensuales();
    }//GEN-LAST:event_btnIngresosMensualesActionPerformed

    private void btnOcupacionConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupacionConsultoriosActionPerformed
        mostrarOcupacionConsultorios();
    }//GEN-LAST:event_btnOcupacionConsultoriosActionPerformed

    private void btnProduccionMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduccionMedicosActionPerformed
        mostrarProduccionMedicos();
    }//GEN-LAST:event_btnProduccionMedicosActionPerformed


    private void mostrarIngresosDiarios() {
        LocalDate hoy = LocalDate.now();
        double total = gestionFacturacion.calcularIngresosPorRango(hoy, hoy);

        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════\n");
        sb.append("   REPORTE DE INGRESOS DEL DÍA\n");
        sb.append("═══════════════════════════════════════\n");
        sb.append("Fecha: ").append(hoy).append("\n");
        sb.append("───────────────────────────────────────\n");

        for (Factura f : gestionFacturacion.listarPorFecha(hoy)) {
            if (f.isPagado()) {
                sb.append(String.format("%-15s  S/. %,.2f  %s\n",
                    f.getNumeroFactura(),
                    f.getTotal(),
                    f.getPaciente().getNombreCompleto()));
            }
        }

        sb.append("───────────────────────────────────────\n");
        sb.append(String.format("TOTAL:  S/. %,.2f\n", total));
        sb.append("═══════════════════════════════════════\n");

        txtReporte.setText(sb.toString());
    }

    private void mostrarIngresosMensuales() {
        LocalDate hoy = LocalDate.now();
        LocalDate inicioMes = hoy.withDayOfMonth(1);
        LocalDate finMes = hoy.withDayOfMonth(hoy.lengthOfMonth());
        double total = gestionFacturacion.calcularIngresosPorRango(inicioMes, finMes);

        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════\n");
        sb.append("   REPORTE DE INGRESOS DEL MES\n");
        sb.append("═══════════════════════════════════════\n");
        sb.append("Período: ").append(inicioMes).append(" al ").append(finMes).append("\n");
        sb.append(String.format("TOTAL:  S/. %,.2f\n", total));
        sb.append("═══════════════════════════════════════\n");

        txtReporte.setText(sb.toString());
    }

    private void mostrarOcupacionConsultorios() {
        LocalDate hoy = LocalDate.now();
        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════\n");
        sb.append("   OCUPACIÓN DE CONSULTORIOS\n");
        sb.append("═══════════════════════════════════════\n");
        sb.append("Fecha: ").append(hoy).append("\n");
        sb.append("───────────────────────────────────────\n");

        for (Consultorio consultorio : gestionConsultorios.listarTodos()) {
            sb.append("\n").append(consultorio.getCodigo())
                .append(" - ").append(consultorio.getNombre())
                .append(" (").append(consultorio.getEspecialidad()).append(")\n");
            sb.append("Estado: ").append(consultorio.getEstado()).append("\n");
            
            int citasOcupadas = 0;
            Map<LocalTime, String> horarioOcupado = new HashMap<>();
            
            for (Cita cita : gestionCitas.listarPorFecha(hoy)) {
                if (cita.getConsultorio() != null && 
                    cita.getConsultorio().getCodigo().equals(consultorio.getCodigo()) &&
                    cita.getEstado() != EstadoCita.CANCELADA) {
                    citasOcupadas++;
                    horarioOcupado.put(cita.getFechaHora().toLocalTime(), 
                                      cita.getPaciente().getNombreCompleto());
                }
            }
            
            sb.append("Citas programadas hoy: ").append(citasOcupadas).append("\n");
            
            if (citasOcupadas > 0) {
                sb.append("Horarios ocupados:\n");
                java.util.List<Map.Entry<LocalTime, String>> listaHorarios = new java.util.ArrayList<>(horarioOcupado.entrySet());
                
                for (int i = 0; i < listaHorarios.size() - 1; i++) {
                    for (int j = 0; j < listaHorarios.size() - i - 1; j++) {
                        if (listaHorarios.get(j).getKey().isAfter(listaHorarios.get(j + 1).getKey())) {
                            Map.Entry<LocalTime, String> temp = listaHorarios.get(j);
                            listaHorarios.set(j, listaHorarios.get(j + 1));
                            listaHorarios.set(j + 1, temp);
                        }
                    }
                }
                
                for (int i = 0; i < listaHorarios.size(); i++) {
                    Map.Entry<LocalTime, String> entry = listaHorarios.get(i);
                    sb.append("  ")
                        .append(entry.getKey())
                        .append(" - ")
                        .append(entry.getValue())
                        .append("\n");
                }
            }
        }

        sb.append("\n═══════════════════════════════════════\n");
        txtReporte.setText(sb.toString());
    }

    private void mostrarProduccionMedicos() {
        LocalDate hoy = LocalDate.now();
        LocalDate inicioMes = hoy.withDayOfMonth(1);
        LocalDate finMes = hoy.withDayOfMonth(hoy.lengthOfMonth());
        
        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════\n");
        sb.append("   PRODUCCIÓN POR MÉDICO\n");
        sb.append("═══════════════════════════════════════\n");
        sb.append("Período: ").append(inicioMes).append(" al ").append(finMes).append("\n");
        sb.append("───────────────────────────────────────\n");

        for (Medico medico : gestionEmpleados.listarMedicos()) {
            sb.append("\n").append(medico.getNombreCompleto())
                .append(" - ").append(medico.getEspecialidad()).append("\n");
            
            int numConsultas = 0;
            for (Consulta consulta : gestionConsultas.listarPorFecha(inicioMes)) {
                if (consulta.getCita().getMedico().equals(medico)) {
                    LocalDate fechaConsulta = consulta.getFechaHoraInicio().toLocalDate();
                    if (!fechaConsulta.isBefore(inicioMes) && !fechaConsulta.isAfter(finMes)) {
                        numConsultas++;
                    }
                }
            }
            
            int numFacturas = 0;
            double totalFacturado = 0;
            for (Factura factura : gestionFacturacion.listarPorFecha(inicioMes)) {
                if (factura.getConsulta() != null && 
                    factura.getConsulta().getCita().getMedico().equals(medico)) {
                    LocalDate fechaFactura = factura.getFechaEmision().toLocalDate();
                    if (!fechaFactura.isBefore(inicioMes) && !fechaFactura.isAfter(finMes)) {
                        numFacturas++;
                        if (factura.isPagado()) {
                            totalFacturado += factura.getTotal();
                        }
                    }
                }
            }
            
            sb.append("  Consultas realizadas: ").append(numConsultas).append("\n");
            sb.append("  Facturas emitidas: ").append(numFacturas).append("\n");
            sb.append(String.format("  Total facturado: S/. %,.2f\n", totalFacturado));
        }

        sb.append("\n═══════════════════════════════════════\n");
        txtReporte.setText(sb.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresosDiarios;
    private javax.swing.JButton btnIngresosMensuales;
    private javax.swing.JButton btnOcupacionConsultorios;
    private javax.swing.JButton btnProduccionMedicos;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtReporte;
    // End of variables declaration//GEN-END:variables
}
